package org.lsst.ccs.integrationgantrygui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author tonyj
 */
public class IntegrationGantryFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private static final int ICON_SIZE = 24;

    private final ImageComponent[] imageComponents;
    private final JLabel[] labels;
    private final ScalableImageProvider[] imageProvider;
    private ScalableImageProvider.Scaling scaling = ScalableImageProvider.Scaling.LOG;
    private final JLabel[] axes;

    /**
     * Creates new form IntegrationGantryFrame
     */
    public IntegrationGantryFrame() {
        initComponents();
        displayComboBox.setModel(new DefaultComboBoxModel(ScalableImageProvider.Scaling.values()));
        displayComboBox.setSelectedItem(ScalableImageProvider.Scaling.LOG);
        imageComponents = new ImageComponent[]{imageComponent1, imageComponent2, imageComponent3, imageComponent4};
        labels = new JLabel[]{jLabel1, jLabel2, jLabel3, jLabel4};
        axes = new JLabel[]{topCoordinateLabel, bottomCoordinateLabel, rightCoordinateLabel, leftCoordinateLabel};
        imageProvider = new ScalableImageProvider[4];
    }

    void setImage(int i, ScalableImageProvider image) {
        imageProvider[i] = image;
        imageComponents[i].setImage(image.createScaledImage(scaling));
    }

    void setLabel(int i, String text) {
        labels[i].setText(text);
    }

    void setFPS(int fps) {
        SwingUtilities.invokeLater(() -> {
            fpsTextBox.setText(String.valueOf(fps));
            fpsTextBox.setForeground(fps < 1 ? Color.RED : Color.BLACK);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        displayComboBox = new javax.swing.JComboBox<>();
        fpsTextBox = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        coordinatePanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imageComponent1 = new org.lsst.ccs.integrationgantrygui.ImageComponent();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imageComponent2 = new org.lsst.ccs.integrationgantrygui.ImageComponent();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        imageComponent3 = new org.lsst.ccs.integrationgantrygui.ImageComponent();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        imageComponent4 = new org.lsst.ccs.integrationgantrygui.ImageComponent();
        topCoordinateLabel = new javax.swing.JLabel();
        bottomCoordinateLabel = new javax.swing.JLabel();
        rightCoordinateLabel = new javax.swing.JLabel();
        leftCoordinateLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewCoordinatesMenuItem = new javax.swing.JCheckBoxMenuItem();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Integration Gantry Cameras");
        setPreferredSize(new java.awt.Dimension(800, 800));

        displayComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayComboBoxActionPerformed(evt);
            }
        });

        fpsTextBox.setColumns(3);
        fpsTextBox.setText("100");

        jLabel5.setText("Frames Per Second:");

        jLabel6.setText("Image scaling:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpsTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpsTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.SOUTH);

        coordinatePanel.setLayout(new java.awt.BorderLayout());

        imagePanel.setLayout(new java.awt.GridLayout(2, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera 1"));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        imageComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent1MouseClicked(evt);
            }
        });
        jPanel2.add(imageComponent1, java.awt.BorderLayout.CENTER);

        imagePanel.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera 2"));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jLabel2, java.awt.BorderLayout.NORTH);

        imageComponent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent2MouseClicked(evt);
            }
        });
        jPanel3.add(imageComponent2, java.awt.BorderLayout.CENTER);

        imagePanel.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera 3"));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jLabel3, java.awt.BorderLayout.NORTH);

        imageComponent3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent3MouseClicked(evt);
            }
        });
        jPanel4.add(imageComponent3, java.awt.BorderLayout.CENTER);

        imagePanel.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera 4"));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jLabel4, java.awt.BorderLayout.NORTH);

        imageComponent4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageComponent4MouseClicked(evt);
            }
        });
        jPanel5.add(imageComponent4, java.awt.BorderLayout.CENTER);

        imagePanel.add(jPanel5);

        coordinatePanel.add(imagePanel, java.awt.BorderLayout.CENTER);

        topCoordinateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topCoordinateLabel.setIcon(new org.lsst.ccs.integrationgantrygui.icon.ArrowUp(ICON_SIZE,ICON_SIZE));
        topCoordinateLabel.setText("+X");
        coordinatePanel.add(topCoordinateLabel, java.awt.BorderLayout.NORTH);

        bottomCoordinateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bottomCoordinateLabel.setIcon(new org.lsst.ccs.integrationgantrygui.icon.ArrowDown(ICON_SIZE,ICON_SIZE));
        bottomCoordinateLabel.setText("-X");
        coordinatePanel.add(bottomCoordinateLabel, java.awt.BorderLayout.PAGE_END);

        rightCoordinateLabel.setIcon(new org.lsst.ccs.integrationgantrygui.icon.ArrowRight(ICON_SIZE,ICON_SIZE));
        rightCoordinateLabel.setText("+Y");
        rightCoordinateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightCoordinateLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        coordinatePanel.add(rightCoordinateLabel, java.awt.BorderLayout.LINE_END);

        leftCoordinateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftCoordinateLabel.setIcon(new org.lsst.ccs.integrationgantrygui.icon.ArrowLeft(ICON_SIZE,ICON_SIZE));
        leftCoordinateLabel.setText("-Y");
        leftCoordinateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftCoordinateLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        coordinatePanel.add(leftCoordinateLabel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(coordinatePanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        viewMenu.setText("View");

        viewCoordinatesMenuItem.setSelected(true);
        viewCoordinatesMenuItem.setText("Show Coordinate Axes");
        viewCoordinatesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoordinatesMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(viewCoordinatesMenuItem);

        jMenuBar1.add(viewMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayComboBoxActionPerformed
        ScalableImageProvider.Scaling newScaling = displayComboBox.getItemAt(displayComboBox.getSelectedIndex());
        this.scaling = newScaling;
        for (int i = 0; i < 4; i++) {
            if (imageComponents != null) {
                imageComponents[i].setImage(imageProvider[i].createScaledImage(newScaling));
            }
        }
    }//GEN-LAST:event_displayComboBoxActionPerformed

    private void imageComponent4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent4MouseClicked
        imageComponentMouseClicked(evt, 3);
    }//GEN-LAST:event_imageComponent4MouseClicked

    private void imageComponent3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent3MouseClicked
        imageComponentMouseClicked(evt, 2);
    }//GEN-LAST:event_imageComponent3MouseClicked

    private void imageComponent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent2MouseClicked
        imageComponentMouseClicked(evt, 1);
    }//GEN-LAST:event_imageComponent2MouseClicked

    private void imageComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageComponent1MouseClicked
        imageComponentMouseClicked(evt, 0);
    }//GEN-LAST:event_imageComponent1MouseClicked

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void viewCoordinatesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoordinatesMenuItemActionPerformed
        for (JLabel label : axes) {
            label.setVisible(viewCoordinatesMenuItem.isSelected());
        }
        validate();
        repaint();
    }//GEN-LAST:event_viewCoordinatesMenuItemActionPerformed

    private void imageComponentMouseClicked(java.awt.event.MouseEvent evt, int position) {
        if (evt.getClickCount() == 2) {
            Container imagePanel = evt.getComponent().getParent();
            if (imagePanel.getParent() == coordinatePanel) {
                coordinatePanel.remove(imagePanel);
                coordinatePanel.add(imagePanel, BorderLayout.CENTER);
                imagePanel.add(imagePanel, position);
            } else {
                imagePanel.remove(imagePanel);
                coordinatePanel.remove(imagePanel);
                coordinatePanel.add(imagePanel, BorderLayout.CENTER);
            }
            coordinatePanel.validate();
            this.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegrationGantryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IntegrationGantryFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottomCoordinateLabel;
    private javax.swing.JPanel coordinatePanel;
    private javax.swing.JComboBox<ScalableImageProvider.Scaling> displayComboBox;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fpsTextBox;
    private org.lsst.ccs.integrationgantrygui.ImageComponent imageComponent1;
    private org.lsst.ccs.integrationgantrygui.ImageComponent imageComponent2;
    private org.lsst.ccs.integrationgantrygui.ImageComponent imageComponent3;
    private org.lsst.ccs.integrationgantrygui.ImageComponent imageComponent4;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel leftCoordinateLabel;
    private javax.swing.JLabel rightCoordinateLabel;
    private javax.swing.JLabel topCoordinateLabel;
    private javax.swing.JCheckBoxMenuItem viewCoordinatesMenuItem;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables

}
